# Generated by Django 5.0.2 on 2024-02-12 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "group",
                    models.CharField(
                        blank=True,
                        help_text="Group designation for targeted holidays",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("half_day", "Half Day"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "punctuality_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Punctuality/Attendance bonus for the day",
                        max_digits=10,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="Employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="Overtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("in_time", models.TimeField()),
                ("out_time", models.TimeField()),
                (
                    "is_half_day",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the work duration was less than standard, marking it as a half day",
                    ),
                ),
                (
                    "total_overtime",
                    models.DurationField(
                        blank=True,
                        help_text="Calculated as the difference between OUT and IN time",
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtimes",
                        to="Employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
