# Generated by Django 5.0.2 on 2024-02-12 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_CNIC",
            new_name="employee_CNIC",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_Designation",
            new_name="employee_Designation",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_Holiday",
            new_name="employee_Holiday",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_JobDescription",
            new_name="employee_JobDescription",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_Last_name",
            new_name="employee_Last_name",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_Salary",
            new_name="employee_Salary",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_holiday_group",
            new_name="employee_holiday_group",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_name",
            new_name="employee_name",
        ),
    ]
