# Generated by Django 5.0.2 on 2024-02-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_records",
                        to="Employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="SalesTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("actual_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "achievement_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Automatically calculated as actual/target * 100",
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_targets",
                        to="Employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "employee"],
                "unique_together": {("employee", "month")},
            },
        ),
    ]
